- name: Install packages
  yum:
    name: 
        - epel-release
        - net-tools
        - vim
        - wget
        - telnet
        - git
        - openssl
        - python36
        - python36-pip
        - MySQL-python
    state: present

- name: Install python packages
  yum:
    name:
        - python
        - python-pip
    state: present

- name: Install pip packages
  pip:
    name:
        - pymysql
    executable: pip-3

- name: Disable SELinux
  selinux:
    state: disabled