- name: Install repo MySQL
  yum:
    name: "{{ mysql_repo }}"
    state: latest

- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create a new database for Zabbix Server
  mysql_db:
    name: zabbix
    state: present
    encoding: utf8
    collation: utf8_bin
  tags:
    - zabbix-server

- name: Create Zabbix server MySQL user
  mysql_user:
    name: zabbix
    password: "{{ zbx_database_password }}"
    priv: "zabbix.*:ALL"
    state: present
  tags:
    - zabbix-server

- name: Check if schema for Zabbix Server already loaded
  shell: mysql -u{{ zbx_database_user }} -p{{ zbx_database_password }} zabbix -e "SHOW TABLES LIKE 'users'" -sN
  register: dbstatus
  failed_when: dbstatus.rc == 2
  tags:
    - zabbix-server

- name: Copy schema DB
  shell: cp /usr/share/doc/zabbix-server-mysql-*/create.sql.gz /tmp
  tags:
    - zabbix-server

- name: Import database Zabbix
  mysql_db:
   name: zabbix
   state: import
   target: /tmp/create.sql.gz
  ignore_errors: true
  tags:
    - zabbix-server