- name: Install repo MySQL
  yum:
    name: "{{ mysql_repo }}"
    state: latest

- name: "RedHat | Install Mysql"
  yum:
    name: 
        - mysql-server
        - MySQL-python
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Find MySQL temporary password 
  shell: "grep temporary.*root@localhost /var/log/mysqld.log | sed 's/.*root@localhost: //' | tail -n 1"
  register: mysql_root_password_temp

- name: Debug MySQL temporary password
  debug: 
    msg: "{{ mysql_root_password_temp.stdout }}"

- name: Mysql | Create a new pass for zabbix user
  command: openssl rand -base64 10
  register: mysql_zabbix_pass

- name: Mysql | Display new pass in playbook output
  debug:
      msg: "New zabbix pass: {{mysql_zabbix_pass.stdout}}"
  when: 
    - mysql_zabbix_pass.changed

- name: Set new password from temporary password
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_pass }}'');" --connect-expired-password -uroot -p"{{ mysql_root_password_temp.stdout }}"'
  ignore_errors: true

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  user.root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
    force: no

- name: Create Zabbix server MySQL user
  mysql_user:
    login_host: "{{ zbx_database_address }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_pass }}"
    name: "{{ zbx_database_name }}"
    host: "{{ item }}"
    password: "{{ mysql_zabbix_pass.stdout }}"
    priv: "{{ zbx_database_name }}.*:ALL"
    state: present
  with_items: 
    - localhost
  #no_log: true

- name: Create a new database for Zabbix Server
  mysql_db:
    name: "{{ zbx_database_name }}"
    collation: utf8_bin
    encoding: utf8
    state: present
    login_host: "{{ zbx_database_address }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_pass }}"