- name: Make sure httpd service is running
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Configure Zabbix Server Web
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'

- name: Copy web.zabbix.conf template 
  template:
    src: templates/zabbix_web.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
  notify: restart httpd

- name: Restart httpd
  service:
    name: httpd
    state: restarted

#- name: Start firewall
#  service: 
#    name: firewalld
#    state: started

#- name: Create firewall rule
#  firewalld:
#    port: 80/tcp
#    permanent: yes
#    immediate: yes
#    state: enabled
#- name: Firewalld reload
#  command: firewall-cmd --reload