- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Install Centos-scl
  yum:
     name:
       - centos-release-scl
  when: zabbix_version is version_compare('5.0', '==')
   
- name: Enable zabbix-frontend
  shell: yum-config-manager --enable zabbix-frontend
  when: zabbix_version is version_compare('5.0', '==')

- name: "RedHat | Set facts for Zabbix <= 5.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-server-{{ zabbix_server_database }}*"
  when:
    - zabbix_version is version_compare('5.0', '<=')

- name: Install Zabbix packeges
  yum:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-nginx-conf-scl
    - zabbix-web-{{ zabbix_server_database }}-scl
    - zabbix-get
    - zabbix-agent
  when: 
    - zabbix_version is version_compare('5.0', '==')

- name: Install Zabbix packeges
  yum:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-server-{{ zabbix_server_database }}
    - zabbix-web-{{ zabbix_server_database }}
    - zabbix-agent
  when:
    - zabbix_version is version_compare('4.4', '<=')
    
- name: Make sure zabbix-agent service is running
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Make sure zabbix-server service is running
  systemd:
    name: zabbix-server
    state: started
    enabled: yes   

- name: Copy zabbix_server.conf template 
  template:
    src: templates/zabbix_server.conf.44.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted