- name: Make sure httpd service is running
  systemd:
    name: httpd
    state: started
    enabled: yes
  when: zabbix_version is version_compare('4.4', '<=')

- name: Configure httpd.conf
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    regexp: 'DocumentRoot "/var/www/html"'
    line: 'DocumentRoot "/usr/share/zabbix"'
  when: zabbix_version is version_compare('4.4', '<=')
   
- name: Configure Zabbix Server Web
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'

- name: Copy web.zabbix.conf template 
  template:
    src: zabbix_web.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
  notify: restart httpd
  when: zabbix_version is version_compare('4.4', '<=')

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  when: zabbix_version is version_compare('4.4', '<=')

- name: Make sure php service is running
  systemd:
    name: rh-php72-php-fpm
    state: started
    enabled: yes
  when: 
   - zabbix_version is version_compare('5.0', '==')

- name: Copy php.zabbix.conf template 
  template:
    src: templates/zabbix-php44.conf.j2
    dest: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
  when: 
   - zabbix_version is version_compare('5.0', '==')

- name: restart php
  service:
    name: rh-php72-php-fpm
    state: restarted
  when: 
   - zabbix_version is version_compare('5.0', '==')

- name: Make sure nginx service is running
  systemd:
    name: rh-nginx116-nginx
    state: started
    enabled: yes
  when: 
   - zabbix_version is version_compare('5.0', '==')

- name: Copy web.zabbix.conf templates
  template:
    src: templates/zabbix_web.conf44.j2
    dest: /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf
  when: 
   - zabbix_version is version_compare('5.0', '==')

- name: Copy nginx.conf template 
  template:
    src: templates/nginx44.conf.j2
    dest: /etc/opt/rh/rh-nginx116/nginx/nginx.conf
  when: 
   - zabbix_version is version_compare('5.0', '==')

- name: restart nginx
  service:
    name: rh-nginx116-nginx
    state: restarted
  when: 
   - zabbix_version is version_compare('5.0', '==')
